on:
  push:
    branches:
      - main
    paths:
      - "identities/*"

jobs:
  artifact_gen:
    name: "Artifact Generation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: python main.py

  artifact_upload:
    name: "Artifact Upload"
    needs: artifact_gen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: actions/upload-artifact@v4
        with:
          name: "identities"
          path: "identities_finalized.txt"
