on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths: ["identities/**"]

jobs:
  entry_check:
    name: "Entry candidate check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: python check.py
